In [1]:
import numpy  as np 


In [2]:
print(np.__version__)
np.show_config

1.26.4


<function numpy.__config__.show(mode='stdout')>

In [3]:
## 3. Create a null vector of size 10 (★☆☆)

In [4]:
arrays=np.zeros(10).reshape(2,5)
print(arrays)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
#### 4. How to find the memory size of any array (★☆☆)

In [6]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))



800 bytes


In [7]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [8]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [9]:
my_arr=np.zeros(10)
my_arr[4]=1
print(my_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
A=np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
A=np.arange(10,50)
b=A[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
A=np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)



In [17]:
npz=np.nonzero([1,2,0,0,4,0])
print(npz)

(array([0, 1, 4], dtype=int64),)


In [18]:
#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
A=np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#### 12. Create a 3x3x3 array with random values (★☆☆)


In [21]:
randoms=np.random.random((3,3,3))
print(randoms)

[[[0.97675389 0.17798962 0.9038514 ]
  [0.25228512 0.5774304  0.30969432]
  [0.19390944 0.58757943 0.09323202]]

 [[0.01394128 0.29732954 0.25785164]
  [0.07777141 0.21971572 0.8546961 ]
  [0.24163426 0.74961052 0.42325994]]

 [[0.28019177 0.60893314 0.40529445]
  [0.05050591 0.70656092 0.90864162]
  [0.85604738 0.4833392  0.48135124]]]


In [22]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
create=np.random.random((10,10))
createmax,createmin=np.max(create),np.min(create)
print(f"{createmax} and {createmin}")

0.9991915841200462 and 0.009684242455498482


In [24]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
create =np.random.random(30)
mean_=np.mean(create)
print(mean_)

0.44070339128119645


In [26]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
create = np.ones((10,10))
create[1:-1,1:-1]=0
print(create)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
A=np.arange(1,26).reshape(5,5)
B=np.pad(A,pad_width=1,mode="constant",constant_values=0)# pad is used for border
print(B)

[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0 16 17 18 19 20  0]
 [ 0 21 22 23 24 25  0]
 [ 0  0  0  0  0  0  0]]


In [30]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [33]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [35]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
