In [1]:
import numpy as np 


In [2]:
a=np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [3]:
new=np.random.random((2,2))
print(new)

[[0.00916387 0.22568505]
 [0.67047296 0.95220322]]


In [4]:
new1=np.random.randint(1,100,10)
print(new1)

[72 58 61 84  9 86 36 47 43 41]


In [5]:
lists=[1,2,3,4]
arr=np.array(lists)
print(arr) 

[1 2 3 4]


In [6]:
tup=(1,2,3,4)
myarr=np.asarray(tup) 
print(myarr) 

[1 2 3 4]


In [7]:
list_tup=[(1,2,3) ,(2,3,4)]
print(np.asarray(list_tup))

[[1 2 3]
 [2 3 4]]


In [8]:
new_array=np.asarray([[1,2,3],[1,2,3]]).reshape(3,2)
print(new_array)
print(new_array.shape)


[[1 2]
 [3 1]
 [2 3]]
(3, 2)


In [9]:
new_array1=np.asarray([[1,2,3],[1,2,3]])
print(len(new_array1))

2


In [10]:
new=np.array([[1,2,3,5],[4,5,8,4]],dtype=np.int64)
print(new.itemsize)

8


In [11]:
new=np.array([1,2,3,4],ndmin=10)
print(new)
print(new.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [12]:
new=np.array([[1,2,3,5],[4,5,8,4]],dtype=np.int32)
print(new.nbytes)

32


In [13]:
myarr=np.arange(1,10)
print(myarr[1:8:2])

[2 4 6 8]


In [14]:
new_array=np.arange(1,10)
print(new_array) 
print(np.take(new_array,[1,2,5]))


[1 2 3 4 5 6 7 8 9]
[2 3 6]


In [15]:
arr = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr.shape)

(3, 3)


In [16]:
arr1 = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr1[0:2,1:3])


[[2 3]
 [4 5]]


In [17]:
arr2=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[4,5,6]]])
print(arr2[1,1,0:2])



[4 5]


In [18]:
arr1=np.array([1,2,3]) 
arr2=np.array([4,5,6]) 
arr_stack=np.stack((arr1,arr2),axis=0)
print(arr_stack ) 
print( )
arr_stack=np.stack((arr1,arr2),axis=1)
print(arr_stack ) 

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [19]:
arr3=np.random.randint(10, size=(2,3))
arr4=np.random.randint(10, size=(2,3))
arr_stack1=np.vstack((arr3,arr4))
print(arr3)
print() 
print(arr4)
print()
print(arr_stack1)

[[1 7 8]
 [8 2 0]]

[[8 2 0]
 [5 5 7]]

[[1 7 8]
 [8 2 0]
 [8 2 0]
 [5 5 7]]


In [20]:
a=np.arange(1,9)
print(a) 
print()
split_array=np.array_split(a,3)
print(split_array)

[1 2 3 4 5 6 7 8]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [21]:
x = np.arange(16).reshape(4,4)
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
x = np.arange(6).reshape(2,3)
print(x) 
y=x.cumsum(axis=0)
print(y)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 5 7]]


In [23]:
arr=np.array([[62, 96, 50],
       [87, 26, 42]])

print(arr.max())

96


In [24]:
a=np.array([1,0,-1,2])
print(np.absolute(a))

[1 0 1 2]


In [25]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
power=np.power(a,b)
print(power) 

[  1   4  27 256]


In [26]:
square_root=np.sqrt(a)
print(square_root)
print(np.cbrt(b))

[1.         1.41421356 1.73205081 2.        ]
[1.         1.25992105 1.44224957 1.58740105]


In [27]:
arr_3 = np.array([1, 2, 3, 4])
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999]


In [28]:
a=np.asarray([1.2,2.5,6.95])
print(np.floor(a))

[1. 2. 6.]


In [29]:
sum=0
for i in range(1,20):
    sum+=i
print(sum) 

190


In [30]:
print(len(range(1,20)))

19


In [31]:
#search,Searhsorted,Sort array, filter


In [65]:
var=np.array([1,2,3,4,5,62,3,4,5,61,2,3,4])
x=np.where(var==2)
print(x)

(array([ 1, 10], dtype=int64),)


In [71]:
var1=np.array([1,2,3,5,6,7,3])
x1=np.searchsorted(var1,4)
print(x1)

3


In [75]:
var2=np.asarray([1,3,2,4,6,5])
sorts=np.sort(var2)
print(sorts)

[1 2 3 4 5 6]


In [79]:
var3=np.array(["a","c","b","k","e"])
sorts1=np.sort(var3)
print(sorts1)

['a' 'b' 'c' 'e' 'k']


In [83]:
var22=np.asarray([1,3,2,4,6,5])
f=[True,True,False,False,True,False]
filt=var22[f]
print(filt)

[1 3 6]


In [85]:
#shuffle , Unique , resize , Flatten , Ravel 


In [93]:
var1=np.array([1,2,3,4,5,6,7])
shuffled=np.random.shuffle(var1)
print(var1)

[1 5 2 6 4 3 7]


In [105]:
var2=np.array([1,2,3,2,4,5,4,5,6,7,6,7])
ret = np.unique(var2,return_index=True,return_counts=True)
print(ret) 

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 4, 5, 8, 9], dtype=int64), array([1, 2, 1, 2, 2, 2, 2], dtype=int64))


In [113]:
var3=np.arange(1,10)
print(var3)
print() 
new=np.resize(var3,(3,3))
print(new)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [125]:
#flatten (c ,f, a ,k)  
print(new) 
print() 
print(new.flatten(order="C")) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [131]:
#flatten (c ,f, a ,k)  
print(new) 
print() 
print(new.ravel(order="F")) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 4 7 2 5 8 3 6 9]


In [133]:
#insert , # Delete


In [139]:
v=np.array([1,2,3,4,5,6,7])
v1=np.array([[1,2,3,4],[5,6,7,8]])
ins=np.insert(v,(3,6),40)
print(ins) 

[ 1  2  3 40  4  5  6 40  7]


In [155]:
isn=np. insert(v1,2,[6,7],axis=1)
print(isn)

[[1 2 6 3 4]
 [5 6 7 7 8]]


In [159]:
#append
v2=np.append(v,6)
print(v2)

[1 2 3 4 5 6 7 6]


In [189]:
v3=np.append(v1,[[67,8,9,10]],axis=0)
print(v3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [67  8  9 10]]


In [197]:
var=np.array([1,2,4,45])
var1=np.delete(var,3)
print(var1)

[1 2 4]


In [217]:
var1=np.array([[1,2,4,5],[1,2,3,4]])
var12=np.delete(var1,1,axis=1)
print(var12)

[[1 4 5]
 [1 3 4]]


In [219]:

var1 = np.array([[1, 2, 4], [5, 6, 7]])
print("Original array:")
print(var1)

# Delete elements from the 2D array, specifying axis if necessary
var12 = np.delete(var1, 1, axis=1)  # Deletes the second column
print("Array after deletion:")
print(var12)


Original array:
[[1 2 4]
 [5 6 7]]
Array after deletion:
[[1 4]
 [5 7]]


**Matrix in Num** 

In [223]:
new_var=np.matrix([[1,2,3,4],[5,6,7,8]])
print(new_var)

[[1 2 3 4]
 [5 6 7 8]]


In [227]:
tran=np.transpose(new_var)
print(tran)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [237]:
swap=np.swapaxes(tran,0,1)
print(swap) 

[[1 2 3 4]
 [5 6 7 8]]


In [243]:
#inverse
print(np.linalg.inv([[1,2],[3,4]])) 


[[-2.   1. ]
 [ 1.5 -0.5]]


In [249]:
#power , n==0(identity matrix) if n>1(power) if n<1 inverse*power 
a=np.matrix([[1,2],[4,5]])
print(np.linalg.matrix_power(a,2))

[[ 9 12]
 [24 33]]


In [251]:
#determinate
b=np.linalg.det(a)
print(b) 

-2.9999999999999996
